-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- inserts a row into public.users
CREATE OR REPLACE FUNCTION public.handle_new_verified_user()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    VOLATILE SECURITY DEFINER
    COST 100
AS $BODY$
begin
  insert into public.signups (id, email)
  values (new.id, new.email);
  return new;
end;
$BODY$;


-- trigger the function every time a user's email is confirmed
CREATE TRIGGER on_auth_user_email_confirmed
after update of email_confirmed_at on auth.users
for each row
when (old.email_confirmed_at IS NULL AND new.email_confirmed_at IS NOT NULL)
  execute procedure public.handle_new_verified_user();
